### ISSUE TITLE
NPM Package depends on react-hot-loader, but it is not listed as a dependency

### ISSUE THREAD

**Issue by AncientSwordRage** [atropos-tech/material-multi-picker#14]
**Describe the bug**
react-hot-loader is listed as a devdependency, but is required by the transpiled npm package.

**To Reproduce**
1. Install the package from NPM

**Expected behavior**
Running the parent app should not error

**Screenshots**

**Additional context**
Adding react-hot-loader as a dependency of the parent app resolves this. But it feels like either it should not be required or it should be a full dependency.

**Comment by duncan-thacker** [comment]
Good spot. Will fix this one now.

**Comment by duncan-thacker** [comment]
Aha, this is a weird one - it's because babel's transpiled output contains a reference to react-hot-loader. I'll make it so the published code doesn't have that.
